server:
  port: 10086
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  redis:
    host: xxx.xxx.xxx.xxx
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0
  mail:
    host: smtp.qq.com
    username: xxx@qq.com
    password: xxx
    default-encoding: UTF-8
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.debug: true # 开启日志
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/fantasy
#      username: root
#      password: 123456
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxx.xxx.xxx.xxx:3301/fantasy
        username: root
        password: 123456
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxx.xxx.xxx.xxx:3302/fantasy
        username: root
        password: 123456
#    props:
#      sql:
#        show: true
    masterslave:
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
      load-balance-algorithm-type: round_robin
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jay.fantasy.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
tencent:
  yun:
    secretid: xxx.xxx.xxx.xxx
    secretkey: xxx.xxx.xxx.xxx